Generate faulty measurements for one asset
In preparation for using the anomaly detection feature, one of the
assets in the factory demo will generate random anomalous measurements.

diff --git a/iotsitewise/factory_demo/create-sitewise-resources b/iotsitewise/factory_demo/create-sitewise-resources
--- a/iotsitewise/factory_demo/create-sitewise-resources
+++ b/iotsitewise/factory_demo/create-sitewise-resources
@@ -22,6 +22,11 @@ while getopts 'd:p:s:g:h' OPT; do
 done
 shift $((OPTIND - 1))
 
+if [ "$num_generators" -lt 2 ]; then
+    echo 'ERROR - Two or more generators are needed, since one will be faulty'
+    exit 1
+fi
+
 
 MEAS_GEN_STACK="DemoFactoryMeasurementGen"
 cfn_output=$(aws cloudformation describe-stacks --stack-name $MEAS_GEN_STACK --query 'Stacks[].Outputs' --output text 2>&1)
@@ -30,8 +35,11 @@ if [[ "$cfn_output" == *"does not exist"* ]]; then
     exit 1
 fi
 
-meas_gen_function_name=$(echo "$cfn_output" | awk '/MeasurementGenLambdaName/ {print $2}')
+meas_gen_function_name=$(echo "$cfn_output" | awk '/\<MeasurementGenLambdaName\>/ {print $2}')
 meas_gen_invoker_rule=$(echo "$cfn_output" | awk '/MeasurementGenInvokerRuleName/ {print $2}')
+anomaly_meas_gen_function_name=$(echo "$cfn_output" | awk '/AnomalyMeasurementGenLambdaName/ {print $2}')
+bucket_name=$(echo "$cfn_output" | awk '/BucketName/ {print $2}')
+bulk_import_role_arn=$(echo "$cfn_output" | awk '/BulkImportRoleArn/ {print $2}')
 cw_sender_function_name=$(echo "$cfn_output" | awk '/CloudWatchSenderLambdaName/ {print $2}')
 cw_alarm_sw_sender_function_name=$(echo "$cfn_output" | awk '/CWAlarmSiteWiseSenderLambdaName/ {print $2}')
 cw_alarm_sns_topic_arn=$(echo "$cfn_output" | awk '/CWALarmMonitoringSNSTopicArn/ {print $2}')
@@ -45,6 +53,9 @@ config=$(cat <<EOF
    "resource_name_prefix": "$prefix",
    "meas_gen_function_name": "$meas_gen_function_name",
    "meas_gen_invoker_rule": "$meas_gen_invoker_rule",
+   "anomaly_meas_gen_function_name": "$anomaly_meas_gen_function_name",
+   "bucket_name": "$bucket_name",
+   "bulk_import_role_arn": "$bulk_import_role_arn",
    "cw_sender_function_name": "$cw_sender_function_name",
    "cw_alarm_sw_sender_function_name": "$cw_alarm_sw_sender_function_name",
    "cw_alarm_sns_topic_arn": "$cw_alarm_sns_topic_arn",
@@ -70,11 +81,14 @@ python sitewise/create_asset_models.py -d $db_file
 python sitewise/create_interfaces.py -d $db_file
 python sitewise/create_assets.py -d $db_file
 python sitewise/associate_assets.py -d $db_file
+python datagen/gen_hist_and_anomaly_data.py -d $db_file
 python lambda/update_lambdas.py -d $db_file
+./enable-meas-gen -d $db_file --start
 python sitewise/create_cw_alarm.py -d $db_file
+python datagen/bulk_import_hist_data.py -d $db_file
 
-echo 'Command to start MeasurementGenInvoker:'
-echo "> ./enable-meas-gen -d $db_file --start"
+echo 'Command to stop MeasurementGenInvoker:'
+echo "> ./enable-meas-gen -d $db_file --stop"
 
 # Format DB file
 tmp_file=$(mktemp)
